/**
 * site_settings keys readable by anon / public RSC clients.
 * Staff (admin/editor) may read all keys via RLS role check.
 *
 * Keep in sync with supabase/reset.sql policy "site_settings_public_read".
 * Admin-only examples: label_billing_*, invite_link_expiry_hours.
 */

export const SITE_SETTINGS_ADMIN_ONLY_KEYS = [
  'label_billing_street',
  'label_billing_postal_code',
  'label_billing_city',
  'label_billing_country',
  'invite_link_expiry_hours',
] as const

/** All keys that public pages need (everything mapped by getSiteSettings except admin-only). */
export const SITE_SETTINGS_PUBLIC_KEYS = [
  'label_name',
  'label_short_name',
  'label_tagline',
  'contact_email',
  'privacy_policy_url',
  'terms_url',
  'instagram_url',
  'youtube_url',
  'spotify_url',
  'spotify_playlist_uri',
  'spotify_playlists',
  'hero_badge',
  'hero_news_badge',
  'hero_description',
  'hero_content_type',
  'hero_featured_id',
  'hero_custom_bg_url',
  'hero_default_primary_btn_label',
  'hero_default_secondary_btn_label',
  'seo_title',
  'seo_description',
  'og_title',
  'og_description',
  'impressum_company_name',
  'impressum_legal_form',
  'impressum_representative',
  'impressum_address',
  'impressum_vat_id',
  'impressum_register_court',
  'impressum_register_number',
  'impressum_phone',
  'impressum_email',
  'datenschutz_content',
  'datenschutz_content_en',
  'agb_content',
  'agb_content_en',
  'portal_terms_version',
  'consent_placeholder_url',
  'noise_opacity',
  'crt_scanlines_enabled',
  'vignette_intensity',
  'shopify_store_url',
  'submit_hub_url',
  'submit_hub_label',
  'submit_hub_description',
  'submit_hub_section_heading',
  'show_about_in_header',
  'show_about_in_footer',
  'about_nav_label',
  'youtube_channel_id',
  'carousel_autoplay_ms',
  'videos_per_page',
  'videos_link_to_page',
  'exclude_shorts_from_public',
  'concerts_per_page',
  'concerts_link_to_page',
  'feature_toggles',
  'logo_url',
  'favicon_url',
  'about_headline',
  'about_subheading',
  'about_body',
  'newsletter_heading',
  'newsletter_description',
  'spotify_section_heading',
  'spotify_section_subheading',
  'videos_section_heading',
  'videos_section_subheading',
  'news_section_heading',
  'news_section_subheading',
  'concerts_section_heading',
  'concerts_section_subheading',
  'releases_section_heading',
  'releases_section_subheading',
  'homepage_section_order',
  'homepage_news_count',
  'contact_topics',
  'custom_social_links',
  'theme_primary',
  'theme_secondary',
  'theme_background',
  'theme_foreground',
  'theme_card',
  'theme_muted',
  'theme_accent',
  'theme_border',
  'theme_gradient_hero_from',
  'theme_gradient_hero_to',
  'theme_gradient_hero_dir',
  'theme_gradient_accent_from',
  'theme_gradient_accent_to',
  'theme_gradient_accent_dir',
  'theme_config',
] as const

export type SiteSettingsPublicKey = (typeof SITE_SETTINGS_PUBLIC_KEYS)[number]
